shared_variables:
  rightholder: Jamit Labs GmbH
  project_name: NewProjectTemplate

default_options:
  lint_fail_level: warning

rules:
  - file_content_regex:
      matching_all:
        Cartfile:
          - "#\\s*[^\\s]+" # Ensure dependencies are commented
          - HandySwift
          - SwiftyUserDefaults
          - SwiftyBeaver
      not_matching_all:
        Cartfile: # Moya already includes Alamofire, prevent redundancy
          - Alamofire
          - Moya
  - file_content_template:
      matching:
        .swiftlint.yml:
          template_url: "https://raw.githubusercontent.com/JamitLabs/ProjLintTemplates/master/iOS/SwiftLint.stencil"
          parameters:
            rightholder: <:rightholder:>
  - file_existence:
      existing_paths:
        - .gitignore
        - .swiftlint.yml
        - README.md
        - LICENSE.md
        - Cartfile
        - Cartfile.private
        - Cartfile.ignore
        - Cartfile.resolved
        - beak.swift
        - SwiftGen-Colors.stencil
        - <:project_name:>.xcodeproj/xcshareddata/IDETemplateMacros.plist
        - App/Sources/AppDelegate.swift
        - App/Sources/Globals/Branding.swift
        - App/Sources/Globals/Logger.swift
        - App/Generated/SwiftGen/Colors.swift
        - App/Generated/SwiftGen/Storyboards.swift
        - App/Generated/SwiftGen/Strings.swift
        - App/SupportingFiles/Info.plist
        - App/Resources/de.lproj/Localizable.strings
        - App/Resources/en.lproj/Localizable.strings
        - App/Resources/Colors.xcassets/Contents.json
        - App/Resources/Images.xcassets/AppIcon.appiconset/Contents.json
        - Tests/SupportingFiles/Info.plist
        - UITests/SupportingFiles/Info.plist
      non_existing_paths:
        - Podfile
        - Podfile.lock
