shared_variables:
  rightholder: Jamit Labs GmbH
  project_name: NewProjectTemplate

rules:
  - xcode_build_phases:
      project_path: <:project_name:>.xcodeproj
      target_name: App
      run_scripts:
        BartyCrouch: |
          if which bartycrouch > /dev/null; then
              # Incrementally update all Storyboards/XIBs strings files
              bartycrouch interfaces -p "$PROJECT_DIR/App/Sources"

              # Add new keys to Localizable.strings files from NSLocalizedString in code
              bartycrouch code -p "$PROJECT_DIR/App/Sources" -l "$PROJECT_DIR/App/Resources" -a -s -e

              # Normalize your Strings files to keep them nice and clean
              bartycrouch normalize -p "$PROJECT_DIR/App" -l en -d -w -h -s
          else
              echo "warning: BartyCrouch not installed, download it from https://github.com/Flinesoft/BartyCrouch"
          fi

        SwiftGen: |
          if which swiftgen > /dev/null; then
              swiftgen strings "$PROJECT_DIR/App/Resources/en.lproj/Localizable.strings" -t structured-swift4 -o "$PROJECT_DIR/App/Generated/SwiftGen/Strings.swift"
              swiftgen storyboards "$PROJECT_DIR/App/Sources" -t swift4 -o "$PROJECT_DIR/App/Generated/SwiftGen/Storyboards.swift"
              swiftgen xcassets "$PROJECT_DIR/App/Resources/Colors.xcassets" -p "$PROJECT_DIR/SwiftGen-Colors.stencil" -o "$PROJECT_DIR/App/Generated/SwiftGen/Colors.swift"
          else
              echo "warning: SwiftGen not installed, download it from https://github.com/AliSoftware/SwiftGen"
          fi

        SwiftLint: |
          if which swiftlint > /dev/null; then
              swiftlint
          else
              echo "warning: SwiftLint not installed, download it from https://github.com/realm/SwiftLint"
          fi

        ProjLint: |
          if which projlint > /dev/null; then
              projlint lint --xcode
          else
              echo "warning: ProjLint not installed, download it from https://github.com/JamitLabs/ProjLint"
          fi

  - xcode_project_navigator:
      project_path: <:project_name:>.xcodeproj
      sorted:
        - App/Sources
        - App/Resources
        - App/SupportingFiles
        - App/Generated
        - Tests/Sources
        - Tests/Resources
        - Tests/SupportingFiles
        - UITests/Sources/
        - UITests/Resources
        - UITests/SupportingFiles
      inner_group_order:
        - assets
        - entitlements
        - plists
        - strings
        - others
        - [code_files, interfaces]
        - folders
      structure:
        - App:
            - Sources:
                - AppDelegate.swift
                - Globals:
                    - Extensions
            - Resources:
                - Colors.xcassets
                - Images.xcassets
                - Localizable.strings
                - Fonts
            - SupportingFiles:
                - LaunchScreen.storyboard
                - Info.plist
            - Generated:
                - SwiftGen
        - Tests:
            - Sources
            - Resources
            - SupportingFiles:
                - Info.plist
        - UITests:
            - Sources
            - Resources
            - SupportingFiles:
                - Info.plist
        - Extensions
        - RootFiles:
            - beak.swift
            - .projlint.yml
            - .swiftlint.yml
            - Cartfile
            - Cartfile.ignore
            - Cartfile.private
            - Cartfile.resolved
            - SwiftGen-Colors.stencil
        - Frameworks:
            - Carthage:
                - App
                - Tests
            - Local:
                - App
                - Tests
        - Products
  - file_content_regex:
      matching_all:
        Cartfile:
          - "#\\s*[^\\s]+" # Ensure dependencies are commented
          - HandySwift
          - SwiftyUserDefaults
          - SwiftyBeaver
      not_matching_all:
        Cartfile: # Moya already includes Alamofire, prevent redundancy
          - Alamofire
          - Moya
  - file_content_template:
      matching:
        .swiftlint.yml:
          template_url: "https://raw.githubusercontent.com/JamitLabs/ProjLintTemplates/master/iOS/SwiftLint.stencil"
          parameters:
            rightholder: <:rightholder:>
        .projlint.yml:
          template_url: "https://raw.githubusercontent.com/JamitLabs/ProjLintTemplates/master/iOS/ProjLint.stencil"
          parameters:
            rightholder: <:rightholder:>
            project_name: <:project_name:>
  - file_existence:
      existing_paths:
        - .gitignore
        - .swiftlint.yml
        - README.md
        - LICENSE.md
        - Cartfile
        - Cartfile.private
        - Cartfile.ignore
        - Cartfile.resolved
        - beak.swift
        - SwiftGen-Colors.stencil
        - <:project_name:>.xcodeproj/xcshareddata/IDETemplateMacros.plist
        - App/Sources/AppDelegate.swift
        - App/Sources/Globals/Branding.swift
        - App/Sources/Globals/Logger.swift
        - App/Generated/SwiftGen/Colors.swift
        - App/Generated/SwiftGen/Storyboards.swift
        - App/Generated/SwiftGen/Strings.swift
        - App/SupportingFiles/Info.plist
        - App/Resources/de.lproj/Localizable.strings
        - App/Resources/en.lproj/Localizable.strings
        - App/Resources/Colors.xcassets/Contents.json
        - App/Resources/Images.xcassets/AppIcon.appiconset/Contents.json
        - Tests/SupportingFiles/Info.plist
        - UITests/SupportingFiles/Info.plist
      non_existing_paths:
        - Podfile
        - Podfile.lock
