opt_in_rules:
- attributes
- closure_end_indentation
- closure_spacing
- empty_count
- explicit_init
- file_header
- first_where
- let_var_whitespace
- nimble_operator
- no_extension_access_modifier
- number_separator
- object_literal
- operator_usage_whitespace
- overridden_super_call
- private_outlet
- prohibited_super_call
- redundant_nil_coalescing
- sorted_imports
- switch_case_on_newline
- trailing_closure
- unneeded_parentheses_in_closure_argument
- vertical_parameter_alignment_on_call

disabled_rules:
- todo

included:
- App/Sources
- Tests/Sources
- UITests/Sources

identifier_name:
  excluded:
    - id

line_length: 160

file_header:
  required_pattern: |
                    \/\/
                    \/\/  Created by [^\(\)\d\n]+ on \d{1,2}\.\d{1,2}\.\d{2}\.
                    \/\/  Copyright © \d{4} Jamit Labs GmbH\. All rights reserved\.
                    \/\/

custom_rules:
  closing_brace_whitespace:
    included: ".*.swift"
    regex: '(?:\n| {2,})\}\)? *\n *[^ \n\})\]s#]'
    name: "Closing Brace Whitespace"
    message: "Empty line required after closing curly braces if code with same indentation follows."
    severity: warning
  closure_params_parantheses:
    included: ".*.swift"
    regex: '\{\s*\([^):]+\)\s*in'
    name: "Unnecessary Closure Params Parantheses"
    message: "Don't use parantheses around non-typed parameters in a closure."
    severity: warning
  debug_log_level:
    included: ".*.swift"
    regex: 'log.debug\('
    name: "Debug Log Level"
    message: "Make sure to remove all debug log levels before committing."
    severity: warning
  dynamic_storyboard_reference:
    included: ".*.swift"
    regex: 'UIStoryboard\(\s*name:\s*\"'
    name: "Dynamic Storyboard Reference"
    message: "Don't use dynamic storyboard references – use SwiftGen & StoryboardScene instead."
    severity: warning
  dynamic_string_reference:
    included: ".*.swift"
    regex: 'NSLocalizedString\s*\('
    name: "Dynamic String Reference"
    message: "Don't use dynamic localization string references via code strings – use SwiftGen & L10n instead."
    severity: warning
  empty_init_body:
    included: ".*.swift"
    regex: 'init\([^\{\n]*\) \{\s+\}'
    name: "Empty Init Body"
    message: "Don't use whitespace or newlines for the body of empty initializers – use `init() {}` instead."
    severity: warning
  empty_method:
    included: ".*.swift"
    regex: 'func [^\s\(]+\([^\{\n]*\) \{\s*\}'
    name: "Empty Method"
    message: "Don't keep empty methods in code without commenting inside why they are needed or a `// TODO: not yet implemented`."
    severity: warning
  empty_type:
    included: ".*.swift"
    regex: '(?:class|protocol|struct|enum) [^\{]+\{\s*\}'
    name: "Empty Type"
    message: "Don't keep empty types in code without commenting inside why they are needed or a `// TODO: not yet implemented`."
    severity: warning
  handyswift_delay:
    included: ".*.swift"
    regex: 'DispatchQueue\.\S+\.asyncAfter\(deadline:'
    name: "HandySwift Delay"
    message: "Use the `delay(by:qosClass:)` method of HandySwift instead of DispatchQueue for delayed code."
    severity: warning
  handyswift_delay_time_interval:
    included: ".*.swift"
    regex: 'delay\(by: ?\d'
    name: "HandySwift Delay TimeInterval"
    message: "Use one of the HandySwift TimeInterval extension methods like `.milliseconds(100)` instead."
    severity: warning
  handyswift_time_interval:
    included: ".*.swift"
    regex: ':\s*(?:Dispatch)?TimeInterval\s*=\s*(?:[1-9]|0\.0*[1-9])'
    name: "HandySwift TimeInterval"
    message: "Use one of the HandySwift (Dispatch)TimeInterval extension methods like `.milliseconds(100)` instead."
    severity: warning
  if_as_guard:
    included: ".*.swift"
    regex: '\n *if [^\{]+\{\s*return\s*(?:nil){0,1}([^a-zA-z\n]*)\n*\s*\}(?! *else)'
    name: "If as Guard"
    message: "Don't use an if statement to just return – use guard for such cases instead."
    severity: warning
  late_force_unwrapping:
    included: ".*.swift"
    regex: '\(\S+\?\.\S+\)!'
    name: "Late Force Unwrapping"
    message: "Don't use ? first to force unwrap later – directly unwrap within the parantheses."
    severity: warning
  local_l10n:
    included: ".*.swift"
    regex: 'func \S+\s*\{\s*[^\}]*let l10n'
    name: "Local l10n"
    message: "Don't name local variable `l10n` – use a property instead and further specify with `localL10n` if needed."
    severity: warning
  log_prefix:
    included: ".*.swift"
    regex: 'log\.(?:verbose|debug|info|warning|error)\("(?:verbose|debug|info|warning|error).*"\)'
    name: "Logging Prefix"
    message: "Don't use logging prefixes with log.verbose/debug/info/warning/error – done automatically."
    severity: warning
  multi_line_parameters:
    included: ".*.swift"
    regex: '(?:func \S+| init)\((?:[^,\n]+,[^{\n)]*\n|\n(?:[^\{\n]*\n)*(?:[^:\n]+:[^,\n]+,){2,}|\n[^{]+\n(?:[^{:\n]+:[^{:\n]+\)[^\n{]+)\{)'
    name: "Multi-Line Parameters"
    message: "Always place a single parameter per line if you need to break the parameter list to multiple lines."
    severity: warning
  multiple_closure_params:
    included: ".*.swift"
    regex: '\n *(?:[^\.\n=]+\.)+[^\(\s]+\([^\{\n]+\{[^\}\n]+\}\)\s*\{'
    name: "Multiple Closure Params"
    message: "Don't use multiple in-line closures – save one or more of them to variables instead."
    severity: warning
  none_case_enum:
    included: ".*.swift"
    regex: 'enum\s+[^\{]+\{(?:\s*\/\/[^\n]*)*(?:\s*case\s+[^\n]+)*\s*case\s+none[^\S]'
    name: "Non Case Enum"
    message: "Do not call enum cases `none` as you might run into problems with Optionals of this type."
    severity: warning
  quick_temporary_disabling:
    included: ".*.swift"
    regex: '\sxdescribe\(|\sxcontext\(|\sxit\('
    name: "Quick Temporary Disabling"
    message: "Temporary disabled Quick examples or groups shouldn't be commited."
    severity: warning
  quick_temporary_focus:
    included: ".*.swift"
    regex: '\sfdescribe\(|\sfcontext\(|\sfit\('
    name: "Quick Temporary Focus"
    message: "Temporary focused Quick examples or groups shouldn't be commited."
    severity: warning
  single_line_enum_cases:
    included: ".*.swift"
    regex: 'enum [^\{]+\{\s*(?:\s*\/\/[^\n]*)*\s*case\s+[^,(\n]+,'
    name: "Single Line Enum Cases"
    message: "Use a new line for each enum case."
    severity: warning
  single_line_guard:
    included: ".*.swift"
    regex: 'guard[^\{]{2,80}else\s*\{\s*\n\s*return.{2,40}\}'
    name: "Single Line Guard"
    message: "Use a single line guard for simple checks."
    severity: warning
  swiftybeaver_logging:
    included: ".*.swift"
    regex: 'print\([^\n]+\)'
    name: "SwiftyBeaver Logging"
    message: "Don't use print – use log.verbose/debug/info/warning/error instead."
    severity: warning
  switch_associated_value_style:
    included: ".*.swift"
    regex: 'case\s+[^\(][^\n]*(?:\(let |[^\)], let)'
    name: "Switch Associated Value Style"
    message: "Always put the `let` in front of case – even if only one associated value captured."
    severity: warning
  too_much_indentation:
    included: ".*.swift"
    regex: '\n {0}[^\s\/][^\n]*[^,|&]\n+ {5,}\S|\n {4}[^\s\/][^\n]*[^,|&]\n+ {9,}\S|\n {8}[^\s\/][^\n]*[^,|&]\n+ {13,}\S|\n {12}[^\s\/][^\n]*[^,|&]\n+ {17,}\S|\n {16}[^\s\/][^\n]*[^,|&]\n+ {21,}\S|\n {20}[^\s\/][^\n]*[^,|&]\n+ {25,}\S'
    name: "Too Much Indentation"
    message: "Don't indent code by more than 4 whitespaces."
    severity: warning
  too_much_unindentation:
    included: ".*.swift"
    regex: ' {28}[^\s\.](.|[^\n]*[^\)][^\ ][^\}])\n+ {0,23}[^\s\/]| {24}[^\s\.](.|[^\n]*[^\)][^\ ][^\}])\n+ {0,19}[^\s\/]| {20}[^\s\.](.|[^\n]*[^\)][^\ ][^\}])\n+ {0,15}[^\s\/]| {16}[^\s\.](.|[^\n]*[^\)][^\ ][^\}])\n+ {0,11}[^\s\/]| {12}[^\s\.](.|[^\n]*[^\)][^\ ][^\}])\n+ {0,7}[^\s\/]| {8}[^\s\.](.|[^\n]*[^\)][^\ ][^\}])\n+ {0,3}[^\s\/]'
    name: "Too Much Unindentation"
    message: "Don't unindent code by more than 4 whitespaces."
    severity: warning
  unnecessary_case_break:
    included: ".*.swift"
    regex: '(case |default)(?:[^\n\}]+\n){2,}\s*break *\n|\n *\n *break(?:\n *\n|\n *\})'
    name: "Unnecessary Case Break"
    message: "Don't use break in switch cases – Swift breaks by default."
    severity: warning
  unnecessary_nil_assignment:
    included: ".*.swift"
    regex: 'var \S+\s*:\s*[^\s]+\?\s*=\s*nil'
    name: "Unnecessary Nil Assignment"
    message: "Don't assign nil as a value when defining an optional type – it's nil by default."
    severity: warning
  vertical_whitespace_between_cases:
    included: ".*.swift"
    regex: '[^\n{][ \t]*\n[ \t]*(?:case[^\n]+|default):[ \t]*\n'
    name: "Vertical Whitespace Between Cases"
    message: "Include a vertical whitespace (empty line) between cases in switch statements."
    severity: warning
  vertical_whitespaces_around_mark:
    included: ".*.swift"
    regex: '\/\/\s*MARK:[^\n]*(\n\n)|(\n\n\n)[ \t]*\/\/\s*MARK:|[^\s{]\n[^\n\/]*\/\/\s*MARK:'
    name: "Vertical Whitespaces Around MARK:"
    message: "Include a single vertical whitespace (empty line) before and none after MARK: comments."
    severity: warning
  vertical_whitespace_opening_braces:
    included: ".*.swift"
    regex: '[{(\[][ \t]*\n[ \t]*\n'
    name: "Vertical Whitespace after Opening Braces"
    message: "Don't include vertical whitespace (empty line) after opening braces."
    severity: warning
  vertical_whitespace_closing_braces:
    included: ".*.swift"
    regex: '\n[ \t]*\n[ \t]*[)}\]]'
    name: "Vertical Whitespace before Closing Braces"
    message: "Don't include vertical whitespace (empty line) before closing braces."
    severity: warning
  whitespace_comment_start:
    included: ".*.swift"
    regex: '[^:#\]\}\)][^:#\]\}\)]\/\/[^\s\/]'
    name: "Whitespace Comment Start"
    message: "A comment should always start with a whitespace."
    severity: warning
